blank_issues_enabled: false
contact_links:
  - name: â“ Ask a question or discuss an idea
    url: https://discord.gg/9CTHRvvA4d
    about: Ask your questions and discuss your ideas in the `#smart-contracts` channel

